### ISSUE TITLE
Final Report To-Do

### ISSUE THREAD

**Issue by Ahmet-Salman** [MuhammedCanKucukaslan/CS-353#5]
#  @Ahmet-Salman and @guvengergerli 
## Implementation
- [x] Tour Dates List Filtering
- [x] Flight Destination/Departure Name Filtering
- [x] Hotel Names Filtering
- [ ] Cities Filtering
- [x] Final List of Tables
- [x] #10
## Report
- [x] A brief description of the program
- [x] User's Manual
- [x] #14

# @MuhammedCanKucukaslan and @MustafaYasirAltunhan Mustafa
## Report Like
- [x] Advanced Query (View/constraint?) 
e.g.
_ALTER TABLE tour_section ADD CONSTRAINT starts_before_end CHECK (start_date<end_date)_ 
- [ ] Final E/R Model
- [x] Implementation Details: The implementation details should include how you have
implemented some important basic concepts in your programming environment, and
any other details you want to mention. For instance, if you use JSP and MySQL, you
can tell about how you connect/access DB (how can you create SQL statements and
send to DB), how you prepare your GUI, how you enforce various constraints, what the
problems/limitations you have encountered are, etc
- [x] At least 2 reports with a complex query (including GROUP BY, MAX, MIN, nested queries) and a nicely formatted output screen:
- written two stored procedures for them, mailed the Çavdar to verify the "complexity" of them. _(sufficiently complex)_
- Also asked if "Sample output reports..." and "At least 2 reports..." refer to same thing _(yes they are)_
- [ ] Sample output reports generated by the system in performing various user operations
update: They are complete however we should dump dummy data to database to obtain sample outputs.
## Implementation
- [x] #9
#### Hotel
- [ ] i. List all available hotels and select the desired one. (apply filters like stars, city, etc.)
- [x] ii. Select the dates for the reservation and indicate the number of guests.
- [x] If a customer makes the reservation, approve or decline it. If declined, state the reason. (employee)
#### Tour Reservation
- [x] Make a tour reservation for a customer.
- [x] Approve or decline tour reservations made by customers themselves. If declined, state the reason.
- [ ] Update a hotel/tour reservation detail
i. Customers cannot update themselves.
ii. Employees can update any detail about the reservation.

### Guide Functionalities: @MuhammedCanKucukaslan 
Completed with #11 
- [x] c. List all available assigned tours. (guide)
- [x] d. Select a tour and accept or decline to guide. (guide)
i. If declined, state the reason.
- [x] e. If accepted, give feedback about the tour. (guide
